name: Publish doc to Wiki

on:
  push:
    branches:
      - main
    paths:
      - 'doc/**'

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Push doc/ to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: doc/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPO: ${{ github.repository }}
